# Generated by Django 3.0.2 on 2020-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
